- name: variables
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: access play level variable
      ansible.builtin.debug:
        msg: url is - {{URL}}
    - name: declaring variable at task level
      ansible.builtin.debug:
        msg: url is - {{URL}}
      vars:
        URL: task.example.com