- name: declaring variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: access play level variable
      ansible.builtin.debug:
        msg: url is - {{URL}}

- name: declaring variable at task level
  hosts: all
  connection: local
  tasks:
    - name: accessing task level variable
      ansible.builtin.debug:
        msg: url is - {{URL}}
      vars:
        URL: task.example.com

- name: declaring variable at file level
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: accessing variable from another file
      ansible.builtin.debug:
        msg: url is - {{URL}}

- name: declaring variable at host file
  hosts: all
  connection: local
  tasks:
    - name: accessing variable from inventory file
      ansible.builtin.debug:
        msg: url is - {{URL}}

- name: ansible facts
  hosts: all
  connection: local
  tasks:
    - name: accessing ansible predefined variables
      ansible.builtin.debug:
        msg: ansible host name == {{ansible_fqdn}}

- name: register a variable
  hosts: all
  connection: local
  tasks:
    - name: register task into register variable
      ansible.builtin.shell: uptime
      register: out
    - name: print out variable
      ansible.builtin.debug:
        msg: "{{out.stdout}}"
    - name: set a fact
      ansible.builtin.set_fact:
        OUTPUT: "{{out.stdout}}"
